# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'wfxr/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'


set-option -g status-position bottom
set -g status-justify centre

unbind C-b
set -g prefix 'C-x'

# u-d-l-r == u-e-i-r
bind M-k split-window -vb -c "#{pane_current_path}"
bind M-j split-window -v -c "#{pane_current_path}"
bind M-h split-window -hb -c "#{pane_current_path}"
bind M-l split-window -h -c "#{pane_current_path}"

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

set -g status-keys emacs
set -g mode-keys vi

# resize the pane
bind -n 'C-Left' resize-pane -L 2
bind -n 'C-Down' resize-pane -D 2
bind -n 'C-Up' resize-pane -U 2
bind -n 'C-Right' resize-pane -R 2
bind C-c copy-mode

# vim-tmux-navigator
set -g @vim_navigator_mapping_left "M-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "M-l"
set -g @vim_navigator_mapping_up "M-k"
set -g @vim_navigator_mapping_down "M-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding


# tmux-continuum



#tmux-power
# light-purple #C08DFF ; light-yellow #F0E58B ; Cyan #8ED0C6
set -g @tmux_power_theme '#8ED0C6'

# rarrow=$(tmux_get '@tmux_power_right_arrow_icon' '')
# larrow=$(tmux_get '@tmux_power_left_arrow_icon' '')
set -g @tmux_power_date_icon           '󰃵'
set -g @tmux_power_time_icon           '󰦖'
set -g @tmux_power_user_icon           '󱢯'
set -g @tmux_power_session_icon        '󱂬'
set -g @tmux_power_right_arrow_icon    ''
set -g @tmux_power_left_arrow_icon     ''
set -g @tmux_power_upload_speed_icon   '󰕒'
set -g @tmux_power_download_speed_icon '󰇚'

set -g @tmux_power_date_format '%F'
set -g @tmux_power_time_format '%T'

set -g @tmux_power_show_upload_speed   true
set -g @tmux_power_show_download_speed true

# 'L' for left only, 'R' for right only and 'LR' for bothset -g status off
set -g @tmux_power_prefix_highlight_pos 'R'

set -g @tmux_power_show_user    true
set -g @tmux_power_show_host    false
set -g @tmux_power_show_session true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

